name: Build, Create Docker Image, Push to DockerHub

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build-test-publish:
    uses: FullStackIndie/Reusable-Workflows/.github/workflows/deploy_static_website.yml@main
    with:
      folder_path: /var/www/html/portfolio
      owner_name: FullStackIndie
      repo_name: Portfolio
    secrets: inherit
 
