name: Build from Github, Deploy to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
 continuous-integration:
    runs-on: ubuntu-latest
    steps:
    - name: Copying files to server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.1
      with:
        server: ${{ secrets.REMOTE_HOST }}
        username:  ${{ secrets.USERNAME }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        local_path: "./*"
        remote_path: "${{ secrets.REMOTE_DIR }}"
        args: '-o ConnectTimeout=5'



    # env:
    #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #   AWS_DEFAULT_REGION: us-west-1

  #   if: github.ref == 'refs/heads/main'
  #   steps:
  # # Step 1
  #     - name: Create CodeDeploy Deployment
  #       run: 
  #        aws deploy create-deployment
  #           --application-name Portfolio
  #           --deployment-group-name Portfolio
  #           --deployment-config-name CodeDeployDefault.OneAtATime
  #           --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
  
  
