name: Build from Github, Deploy to Linux

on:
  push:
    branches: [main]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copying files to server
        uses: appleboy/ssh-action@v0.1.4
        env: 
          dir: ${{ secrets.REMOTE_DIR}}
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.REMOTE_PORT }}
          envs: dir
          script: |
            cp /home/runner/work/Portfolio/Portfolio /var/www/portfolio
          

    # env:
    #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #   AWS_DEFAULT_REGION: us-west-1

    #   if: github.ref == 'refs/heads/main'
    #   steps:
    # # Step 1
    #     - name: Create CodeDeploy Deployment
    #       run:
    #        aws deploy create-deployment
    #           --application-name Portfolio
    #           --deployment-group-name Portfolio
    #           --deployment-config-name CodeDeployDefault.OneAtATime
    #           --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
