name: Deploy to Linux Server

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  create-site-map:
    runs-on: ubuntu-latest
    steps:
      - name: Create a Sitemap
        uses: FullStackIndie/sitemap-generator@v1.2.1
        with:
          url: https://portfolio.fullstackindie.net
          cache-key: sitemap

  build-test-publish:
    needs: create-site-map
    uses: FullStackIndie/Reusable-Workflows/.github/workflows/deploy_static_website_s3_&_cloudfront_invalidation.yml@main
    with:
      folder_path: /var/www/html/portfolio
      repo_name: Portfolio
      source_folder: ./
      dest_folder: Portfolio
      invalidation_paths: /Portfolio/*
    secrets:
      SERVER_SSH_HOST: ${{ secrets.SERVER_SSH_HOST }}
      SERVER_SSH_USERNAME: ${{ secrets.SERVER_SSH_USERNAME }}
      SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
      SERVER_SSH_PORT: ${{ secrets.SERVER_SSH_PORT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
