name: Deploy to Linux Server

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build-test-publish:
    uses: FullStackIndieLLC/Reusable-Workflows/.github/workflows/deploy_static_website_s3_&_cloudfront_invalidation.yml@v1.1.88
    with:
      folder_path: /var/www/html/portfolio
      repo_name: Portfolio
      source_folder: ./
      dest_folder: Portfolio
      invalidation_paths: /Portfolio/*
    secrets:
      SERVER_SSH_HOST: ${{ secrets.SERVER_SSH_HOST }}
      SERVER_SSH_USERNAME: ${{ secrets.SERVER_SSH_USERNAME }}
      SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
      SERVER_SSH_PORT: ${{ secrets.SERVER_SSH_PORT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

  create-site-map:
    needs: build-test-publish
    uses: FullStackIndieLLC/Reusable-Workflows/.github/workflows/create_sitemap_for_static_site_&_upload_to_server.yml@v1.1.88
    with:
      folder_path: /var/www/html/portfolio
      repo_name: Portfolio
      url: https://portfolio.fullstackindie.net
      cache: false
    secrets:
      SERVER_SSH_HOST: ${{ secrets.SERVER_SSH_HOST }}
      SERVER_SSH_USERNAME: ${{ secrets.SERVER_SSH_USERNAME }}
      SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
      SERVER_SSH_PORT: ${{ secrets.SERVER_SSH_PORT }}